### ISSUE TITLE
28 percent showing as 27

### ISSUE THREAD

**Issue by inibg** [pguso/jquery-plugin-circliful#81]
Hi, I was trying the library and I noticed a problem with the percentage number showed when the value is 28. When the value is 28 the chart shows 27.
As far as I could see, the problem is with the floating point when calculating the percentage from the angle. I solved it changing line 151:
        this                    .text(parseInt(angle / 360 * 100) + '%');
   for this                    .text(parseInt(angle * 100 / 360 * 100 / 100) + '%');

**Comment by Alaloterie** [comment]
I have the same problem than inibg
In jquery.circliful.min.js and jquery.circliful.js
I have changed:
 .text(parseInt(angle / 360 * 100) + '%');
by
 .text(parseInt(100*angle / 360 ) + '%');
Thank you inibg

**Comment by pguso** [comment]
@al3x-edge i saw you fixed it on your side, i implemented your change. Next time it would be nice if you share your code and open a pull request.

**Comment by al3x-edge** [comment]
I was actually waiting for the implementation that we pulled from above to make it through all of staging / QA in the project before throwing in a PR to make sure it solved all our cases.  Currently the project is being held up by some external factors.

We appreciate the work that you have put into the library.  I wasn't hiding anything from the project; I forked and kept public and created a reference to this issue. Wanted to make sure the change was tested before just throwing something in.  You could have communicated before chiding me.

**Comment by pguso** [comment]
@al3x-edge sorry i didn't ment to chiding you. It was just a recommendation, you got me wrong.

**Comment by engemasa** [comment]
I think there is still an issue with percentages being off by one or two and there seems to be a developing pattern. Here's what I found thus far:

- Percentage set to: 59, display is 61
- Percentage set to: 60, display is 61
- Percentage set to: 61, display is 61
- Percentage set to: 62, display is 63
- Percentage set to: 64, display is 66
- Percentage set to: 65, display is 66
- Percentage set to: 66, display is 66
- Percentage set to: 67, display is 69
- Percentage set to: 68, display is 69
- Percentage set to: 69, display is 69
- Percentage set to: 70, display is 72
- Percentage set to: 71, display is 72
- Percentage set to: 72, display is 72
- Percentage set to: 73, display is 75

Here's my fiddle: https://jsfiddle.net/engemasa/ujcgxdrg/3/

**Comment by engemasa** [comment]
Bump

**Comment by engemasa** [comment]
After some tinkering around I've discovered that it could be a something to do with the `animationStep` property. Originally set to 5 and the result it as previously mentioned (Percentage set to 60 but the display was 61). I changed the `animationStep` property to 3 and the results were a smoother animation (as expected) and display the correct percentage (unexpected). Win/Win?

**Comment by tamaker** [comment]
Question -- so its confirmed that animation-step can result in WRONG values?   I just discovered my  values were also off slightly and was able to (after reading this) change animation-step to 1 and the values are correct, though the animation takes longer.

**Comment by mlibre** [comment]
yeh. problem still exist. in low animationStep it works fine.

**Comment by HarareBorn** [comment]
I tried setting animationStep to a lower figure but the problem is still there. In my project it's showing 5% as 6%.

var participant = 5;
            alert(participant);

            $("#partInc").circliful({
                animationStep: 4,
                foregroundBorderWidth: 20,
                foregroundColor: "#006150",
                noPercentageSign: true,
                percent: (participant)
            });

That's my test code, the value is set to 5 but shows 6 in the frontend.
